http_interactions:
- recorded_at: Fri, 16 Jan 2026 20:44:39 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"ccm_config":{"data_export_configs":[{"bucket_name":"billing","bucket_region":"us-east-1","report_name":"cost-and-usage-report","report_prefix":"reports","report_type":"CUR2.0"}]}},"type":"ccm_config"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://frog.datadoghq.com/api/v2/integration/aws/accounts/873c7e78-8915-4c7a-a3a7-33a57adf54f4/ccm_config
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"873c7e78-8915-4c7a-a3a7-33a57adf54f4","type":"ccm_config","attributes":{"data_export_configs":[{"report_name":"cost-and-usage-report","report_prefix":"reports","report_type":"CUR2.0","bucket_name":"billing","bucket_region":"us-east-1"}]}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 16 Jan 2026 20:44:39 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://frog.datadoghq.com/api/v2/integration/aws/accounts/%7Baws_account_config_id%7D/ccm_config
  response:
    body:
      encoding: UTF-8
      string: '{"errors":[{"status":"400","title":"Invalid Parameter","detail":"invalid
        parameter \"aws_account_config_id\" in \"path\"; expected type \"uuid\""}]}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 400
      message: Bad Request
recorded_with: VCR 6.0.0
