http_interactions:
- recorded_at: Fri, 16 Jan 2026 20:08:01 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json
    method: GET
    uri: https://frog.datadoghq.com/api/v2/integration/aws/accounts/873c7e78-8915-4c7a-a3a7-33a57adf54f4/ccm_config
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"873c7e78-8915-4c7a-a3a7-33a57adf54f4","type":"ccm_config","attributes":{"data_export_configs":[{"report_name":"cost-and-usage-report","report_prefix":"reports","report_type":"CUR2.0","bucket_name":"billing","bucket_region":"us-east-1"}]}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
