http_interactions:
- recorded_at: Thu, 27 Apr 2023 20:34:59 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/monitor/policy/INVALID_UUID
  response:
    body:
      encoding: UTF-8
      string: '{"errors":["Invalid URL param: policy_id must be an uuid"]}'
    headers:
      Content-Type:
      - application/json
    status:
      code: 400
      message: Bad Request
recorded_with: VCR 6.0.0
