http_interactions:
- recorded_at: Thu, 12 May 2022 09:52:06 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"name":"Test-Delete_an_Application_key_returns_No_Content_response-1652349126"},"type":"application_keys"}}'
    headers:
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/current_user/application_keys
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"application_keys","id":"d2653524-a474-460c-a7c7-75073e8aa1fa","attributes":{"name":"Test-Delete_an_Application_key_returns_No_Content_response-1652349126","created_at":"2022-05-12T09:52:07.427090+00:00","last4":"xxxx","key":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","scopes":null},"relationships":{"owned_by":{"data":{"type":"users","id":"3ad549bf-eba0-11e9-a77a-0705486660d0"}},"leak_information":{"data":null}}}}'
    status:
      code: 201
      message: Created
- recorded_at: Thu, 12 May 2022 09:52:06 GMT
  request:
    body: null
    headers: {}
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/application_keys/d2653524-a474-460c-a7c7-75073e8aa1fa
  response:
    body:
      encoding: UTF-8
      string: ''
    status:
      code: 204
      message: No Content
- recorded_at: Thu, 12 May 2022 09:52:06 GMT
  request:
    body: null
    headers:
      Content-Type:
      - application/json
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/current_user/application_keys/d2653524-a474-460c-a7c7-75073e8aa1fa
  response:
    body:
      encoding: UTF-8
      string: '{"errors": ["Application key not found"]}'
    status:
      code: 404
      message: Not Found
recorded_with: VCR 6.0.0
