http_interactions:
- recorded_at: Tue, 12 Dec 2023 14:24:29 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"account_id":"123456789123","bucket_name":"dd-cost-bucket","bucket_region":"us-east-1","report_name":"dd-report-name","report_prefix":"dd-report-prefix"},"type":"aws_cur_config_post_request"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/cost/aws_cur_config
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"type":"aws_cur_config","id":177,"attributes":{"account_id":"123456789123","bucket_name":"dd-cost-bucket","bucket_region":"us-east-1","report_prefix":"dd-report-prefix","report_name":"dd-report-name","months":15,"updated_at":"2023-12-12T14:24:30.907264","created_at":"2023-12-12T14:24:30.907264","status":"active","status_updated_at":"2023-12-12T14:24:30.904602","error_messages":[]}}}

        '
    headers:
      Content-Type:
      - application/json
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
