http_interactions:
- recorded_at: Tue, 12 Dec 2023 13:33:48 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json
    method: GET
    uri: https://api.datadoghq.com/api/v2/cost/aws_cur_config
  response:
    body:
      encoding: UTF-8
      string: '{"data": [{"type": "aws_cur_config", "id": 100, "attributes": {"account_id":
        "000000000000", "bucket_name": "test_bucket_name", "bucket_region": "us-east-1",
        "report_prefix": "cur-hourly", "report_name": "billing-conductor-cur", "months":
        15, "updated_at": "2023-10-27T12:38:39.585408", "created_at": "2023-10-10T13:53:28.774143",
        "status": "active", "status_updated_at": "2023-11-21T17:07:24.778386", "error_messages":
        []}}]}'
    headers:
      Content-Type:
      - application/json
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
