http_interactions:
- recorded_at: Wed, 14 Dec 2022 08:46:48 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"cases":[{"notifications":["channel"],"status":"info"}],"complianceSignalOptions":{"userActivationStatus":true,"userGroupByFields":["@account_id"]},"isEnabled":false,"message":"ddd","name":"Test-Create_a_cloud_configuration_rule_returns_OK_response-1671007608_cloud","options":{"complianceRuleOptions":{"complexRule":false,"regoRule":{"policy":"package
        datadog\n","resourceTypes":["gcp_compute_disk"]}}},"tags":["my:tag"],"type":"cloud_configuration"}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/security_monitoring/rules
  response:
    body:
      encoding: UTF-8
      string: '{"creationAuthorId":1445416,"tags":["my:tag"],"type":"cloud_configuration","isEnabled":false,"hasExtendedTitle":true,"message":"ddd","options":{"detectionMethod":"threshold","evaluationWindow":7200,"maxSignalDuration":86400,"complianceRuleOptions":{"regoRule":{"policy":"package
        datadog\n","resourceTypes":["gcp_compute_disk"]},"complexRule":false},"keepAlive":21600},"version":1,"createdAt":1671007608778,"filters":[],"queries":[{"query":"resource_type:gcp_compute_disk","groupByFields":["resource_type","resource_id"],"aggregation":"count","name":"a","distinctFields":[]}],"isDeleted":false,"complianceSignalOptions":{"defaultActivationStatus":null,"userActivationStatus":true,"defaultGroupByFields":null,"userGroupByFields":["@account_id"]},"cases":[{"status":"info","notifications":["channel"],"name":"","condition":"a
        > 0"}],"id":"azn-bwu-qdq","isDefault":false,"name":"Test-Create_a_cloud_configuration_rule_returns_OK_response-1671007608_cloud"}

        '
    headers:
      Content-Type:
      - application/json
    status:
      code: 200
      message: OK
- recorded_at: Wed, 14 Dec 2022 08:46:48 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/security_monitoring/rules/azn-bwu-qdq
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
