http_interactions:
- recorded_at: Fri, 28 Nov 2025 10:48:41 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"env":"production","identifier":"my-gate-testdeletedeploymentrulereturnsnocontentresponse1764326921","service":"my-service"},"type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"32ff7c01-1f90-4ae4-bef0-b759f1ad280f","type":"deployment_gate","attributes":{"created_at":"2025-11-28T10:48:41.325741Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate-testdeletedeploymentrulereturnsnocontentresponse1764326921","service":"my-service","updated_at":"2025-11-28T10:48:41.325741Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:41 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"name":"My deployment rule","options":{"excluded_resources":[]},"type":"faulty_deployment_detection"},"type":"deployment_rule"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates/32ff7c01-1f90-4ae4-bef0-b759f1ad280f/rules
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"8229075f-8014-432c-9597-ba549ae5cd83","type":"deployment_rule","attributes":{"created_at":"2025-11-28T10:48:41.470358Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"gate_id":"32ff7c01-1f90-4ae4-bef0-b759f1ad280f","name":"My
        deployment rule","options":{},"type":"faulty_deployment_detection","updated_at":"2025-11-28T10:48:41.470358Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:41 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/32ff7c01-1f90-4ae4-bef0-b759f1ad280f/rules/8229075f-8014-432c-9597-ba549ae5cd83
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
- recorded_at: Fri, 28 Nov 2025 10:48:41 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/32ff7c01-1f90-4ae4-bef0-b759f1ad280f/rules/8229075f-8014-432c-9597-ba549ae5cd83
  response:
    body:
      encoding: UTF-8
      string: '{"errors":[{"status":"404","title":"Not Found","detail":"Rule does
        not exist"}]}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 404
      message: Not Found
- recorded_at: Fri, 28 Nov 2025 10:48:41 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/32ff7c01-1f90-4ae4-bef0-b759f1ad280f
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
