http_interactions:
- recorded_at: Wed, 10 Dec 2025 09:23:51 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"env":"production","identifier":"my-gate-testdeletedeploymentgatereturnsnocontentresponse1765358631","service":"my-service"},"type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"03a2ecd3-87ad-45aa-9dbb-fda1215a4087","type":"deployment_gate","attributes":{"created_at":"2025-12-10T09:23:51.052668Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate-testdeletedeploymentgatereturnsnocontentresponse1765358631","service":"my-service","updated_at":"2025-12-10T09:23:51.052668Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Wed, 10 Dec 2025 09:23:51 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/03a2ecd3-87ad-45aa-9dbb-fda1215a4087
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
- recorded_at: Wed, 10 Dec 2025 09:23:51 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/03a2ecd3-87ad-45aa-9dbb-fda1215a4087
  response:
    body:
      encoding: UTF-8
      string: '{"errors":[{"status":"404","title":"Not Found","detail":"Gate does
        not exist"}]}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 404
      message: Not Found
recorded_with: VCR 6.0.0
