http_interactions:
- recorded_at: Fri, 28 Nov 2025 10:48:42 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"env":"production","identifier":"my-gate-testgetdeploymentrulereturnsokresponse1764326922","service":"my-service"},"type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"701d9655-8d81-43d0-9954-cf24b4959b60","type":"deployment_gate","attributes":{"created_at":"2025-11-28T10:48:43.092215Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate-testgetdeploymentrulereturnsokresponse1764326922","service":"my-service","updated_at":"2025-11-28T10:48:43.092215Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:42 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"name":"My deployment rule","options":{"excluded_resources":[]},"type":"faulty_deployment_detection"},"type":"deployment_rule"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates/701d9655-8d81-43d0-9954-cf24b4959b60/rules
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"c96cd32f-5c92-4bc7-9483-85a824b394a7","type":"deployment_rule","attributes":{"created_at":"2025-11-28T10:48:43.237862Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"gate_id":"701d9655-8d81-43d0-9954-cf24b4959b60","name":"My
        deployment rule","options":{},"type":"faulty_deployment_detection","updated_at":"2025-11-28T10:48:43.237862Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:42 GMT
  request:
    body: null
    headers:
      Accept:
      - application/json
    method: GET
    uri: https://api.datadoghq.com/api/v2/deployment_gates/701d9655-8d81-43d0-9954-cf24b4959b60/rules/c96cd32f-5c92-4bc7-9483-85a824b394a7
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"c96cd32f-5c92-4bc7-9483-85a824b394a7","type":"deployment_rule","attributes":{"created_at":"2025-11-28T10:48:43.237862Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"gate_id":"701d9655-8d81-43d0-9954-cf24b4959b60","name":"My
        deployment rule","options":{},"type":"faulty_deployment_detection","updated_at":"2025-11-28T10:48:43.237862Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:42 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/701d9655-8d81-43d0-9954-cf24b4959b60/rules/c96cd32f-5c92-4bc7-9483-85a824b394a7
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
- recorded_at: Fri, 28 Nov 2025 10:48:42 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/701d9655-8d81-43d0-9954-cf24b4959b60
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
