http_interactions:
- recorded_at: Fri, 28 Nov 2025 10:48:43 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"env":"production","identifier":"my-gate-testupdatedeploymentgatereturnsokresponse1764326923","service":"my-service"},"type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"6080b4ee-0fa6-4370-aafa-adb5b71c2fab","type":"deployment_gate","attributes":{"created_at":"2025-11-28T10:48:43.844073Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate-testupdatedeploymentgatereturnsokresponse1764326923","service":"my-service","updated_at":"2025-11-28T10:48:43.844073Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:43 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false},"id":"12345678-1234-1234-1234-123456789012","type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: PUT
    uri: https://api.datadoghq.com/api/v2/deployment_gates/6080b4ee-0fa6-4370-aafa-adb5b71c2fab
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"6080b4ee-0fa6-4370-aafa-adb5b71c2fab","type":"deployment_gate","attributes":{"created_at":"2025-11-28T10:48:43.844073Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate-testupdatedeploymentgatereturnsokresponse1764326923","service":"my-service","updated_at":"2025-11-28T10:48:44.028502Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Fri, 28 Nov 2025 10:48:43 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/6080b4ee-0fa6-4370-aafa-adb5b71c2fab
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
