http_interactions:
- recorded_at: Tue, 02 Dec 2025 17:12:02 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false,"env":"production","identifier":"my-gate","service":"my-service"},"type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: POST
    uri: https://api.datadoghq.com/api/v2/deployment_gates
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"010e234b-b358-463e-a44d-6fbe29ec3f6b","type":"deployment_gate","attributes":{"created_at":"2025-12-02T17:12:02.374479Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate","service":"my-service","updated_at":"2025-12-02T17:12:02.374479Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Tue, 02 Dec 2025 17:12:02 GMT
  request:
    body:
      encoding: UTF-8
      string: '{"data":{"attributes":{"dry_run":false},"id":"12345678-1234-1234-1234-123456789012","type":"deployment_gate"}}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
    method: PUT
    uri: https://api.datadoghq.com/api/v2/deployment_gates/010e234b-b358-463e-a44d-6fbe29ec3f6b
  response:
    body:
      encoding: UTF-8
      string: '{"data":{"id":"010e234b-b358-463e-a44d-6fbe29ec3f6b","type":"deployment_gate","attributes":{"created_at":"2025-12-02T17:12:02.374479Z","created_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"},"dry_run":false,"env":"production","identifier":"my-gate","service":"my-service","updated_at":"2025-12-02T17:12:02.534024Z","updated_by":{"id":"9919ec9b-ebc7-49ee-8dc8-03626e717cca","name":"CI
        Account","handle":"9919ec9b-ebc7-49ee-8dc8-03626e717cca"}}}}'
    headers:
      Content-Type:
      - application/vnd.api+json
    status:
      code: 200
      message: OK
- recorded_at: Tue, 02 Dec 2025 17:12:02 GMT
  request:
    body: null
    headers:
      Accept:
      - '*/*'
    method: DELETE
    uri: https://api.datadoghq.com/api/v2/deployment_gates/010e234b-b358-463e-a44d-6fbe29ec3f6b
  response:
    body:
      encoding: UTF-8
      string: ''
    headers: {}
    status:
      code: 204
      message: No Content
recorded_with: VCR 6.0.0
