http_interactions:
- recorded_at: Tue, 29 Mar 2022 16:50:57 GMT
  request:
    body: null
    headers:
      Content-Type:
      - application/json
    method: GET
    uri: https://api.datadoghq.com/api/v2/metrics?filter%5Btags%5D=TestListtagconfigurationswithatagfilterreturnsSuccessresponse1648572657
  response:
    body:
      encoding: UTF-8
      string: '{"data":[]}'
    status:
      code: 200
      message: OK
recorded_with: VCR 6.0.0
